name: 🧪 Test Bot

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.9, 3.10]
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v4
      
    - name: 🐍 Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 🧪 Test imports
      run: |
        echo "🔍 Тестирование импортов..."
        python -c "import pandas, numpy, sklearn, ccxt, telegram, tensorflow; print('✅ Все основные библиотеки импортированы')"
        
    - name: 🧪 Test model creation
      run: |
        echo "🧠 Тестирование создания модели..."
        python -c "
        import tensorflow as tf
        import numpy as np
        
        # Создаем простую модель
        model = tf.keras.Sequential([
            tf.keras.layers.LSTM(32, return_sequences=True, input_shape=(12, 5)),
            tf.keras.layers.Dense(5, activation='softmax')
        ])
        
        # Тестируем предсказание
        test_data = np.random.random((1, 12, 5))
        prediction = model.predict(test_data, verbose=0)
        print(f'✅ Модель создана и работает. Размер предсказания: {prediction.shape}')
        "
        
    - name: 🧪 Test configuration
      run: |
        echo "⚙️ Тестирование конфигурации..."
        python -c "
        import json
        
        # Проверяем пример конфигурации
        with open('bot_config.example.json', 'r') as f:
            config = json.load(f)
        
        required_keys = ['telegram_token', 'chat_id', 'binance_api', 'ml_settings']
        for key in required_keys:
            assert key in config, f'Отсутствует ключ: {key}'
        
        print('✅ Конфигурация корректна')
        "
        
    - name: 🧪 Test data structures
      run: |
        echo "📊 Тестирование структур данных..."
        python -c "
        import pandas as pd
        import numpy as np
        
        # Создаем тестовые данные
        data = {
            'close': np.random.randn(100).cumsum() + 100,
            'volume': np.random.exponential(1000, 100),
            'high': np.random.randn(100).cumsum() + 102,
            'low': np.random.randn(100).cumsum() + 98,
            'rsi': np.random.uniform(20, 80, 100)
        }
        
        df = pd.DataFrame(data)
        
        # Тестируем технические индикаторы
        df['ema_20'] = df['close'].ewm(span=20).mean()
        df['rsi'] = 100 - (100 / (1 + df['close'].rolling(14).apply(lambda x: x[x > 0].sum() / abs(x[x < 0]).sum() if len(x[x < 0]) > 0 else 1)))
        
        print(f'✅ Данные созданы: {len(df)} записей, {len(df.columns)} столбцов')
        "
        
    - name: 📊 Test results
      run: |
        echo "🎯 Все тесты пройдены успешно!"
        echo "✅ Python ${{ matrix.python-version }} - совместим"
        echo "✅ Импорты работают"
        echo "✅ Модель создается"
        echo "✅ Конфигурация корректна"
        echo "✅ Структуры данных работают"
